### ISSUE TITLE
Confusing documentation: missing imports

### ISSUE THREAD

**Issue by adericbourg** [algolia/algoliasearch-client-scala#126]
Regarding this documentation: https://www.algolia.com/doc/indexing/import-synchronize-data/scala#importing-through-the-dashboard

The examples do not explicit required imports (`algolia.AlgoliaDsl._`), so they do not compile "as is".

**Comment by ElPicador** [comment]
Thanks for the report, it should be fixed: https://www.algolia.com/doc/indexing/import-synchronize-data/scala#import-your-data
