### ISSUE TITLE
Confusing documentation: variable naming

### ISSUE THREAD

**Issue by adericbourg** [algolia/algoliasearch-client-scala#127]
Regarding this documentation: https://www.algolia.com/doc/indexing/import-synchronize-data/scala#importing-through-the-dashboard

The example uses the same name for three concepts.

```scala
val objects: Traversable[MyObject] = loadObjectsFromDatabaseAsJSONObjects()

objects
  .grouped(1000)
  .map { objects =>
    client.execute {
      index into "myIndex" objects
} //Returns a scala.concurrent.Future
}
```

* `objects` for the `Traversable`
* `objects` as the `map` function parameter
* `objects` as the function from `IndexingDefinition` in `index into "myIndex" objects`

By the way, the line `} //Returns a scala.concurrent.Future` could be indented by two more spaces :)

**Comment by ElPicador** [comment]
Also fixed 😄

**Comment by adericbourg** [comment]
Almost: 

```scala
.map { objects =>
    client.execute {
      index into "myIndex" objects myObjects
    } //Returns a scala.concurrent.Future
```

There are still two confusing references to `objects`.

**Comment by ElPicador** [comment]
Yes, sorry. Should be fixed now
