### ISSUE TITLE
Backup / Retrieve of all index content

### ISSUE THREAD

**Issue by ElPicador** [algolia/algoliasearch-client-scala#15]
You can retrieve all index content for backup purposes or for SEO using the browse method.
This method can retrieve up to 1,000 objects per call and supports full text search and filters but the distinct feature is not available
Unlike the search method, the sort by typo, proximity, geo distance and matched words is not applied, the hits are only sorted by numeric attributes specified in the ranking and the custom ranking.

You can browse the index:

```scala
// Iterate with a filter over the index
Iterator<JSONObject> it = index.browse(new Query("text").setNumericFilters("i<42"));

// Retrieve the next cursor from the browse method
Iterator<JSONObject> it  = index.browseFrom(new Query("text").setNumericFilters("i<42"), "");
System.out.println(it.getCursor());
```

See: https://github.com/algolia/algoliasearch-client-java/blob/master/src/main/java/com/algolia/search/saas/Index.java#L471

**Comment by ElPicador** [comment]
As this client uses `Future`, we might go to a `Iterator[Future[Iterator[A]]]`. It does not seems nice though :/

Anyone has a better idea?

**Comment by redox** [comment]
Indeed, not super nice.

In ruby we do 2 things:

 - for full-export purpose:

```ruby
index.browse(optional_starting_point_cursor = nil) do |hit|
  # process all hits
end
```

 - and for "pagination" purpose, you don't need to iterate on more than the "page" retrieved by the following function:

```ruby
answer = index.browse_from(optional_starting_point_cursor = nil)
```

**Comment by ElPicador** [comment]
Yes for the `"pagination" purpose` we can have a `def browse(): Future[Iterable[A]]` which is ok

But for the `full-export purpose` I don't see another another possibility than: `Iterator[Future[Iterator[A]]]`
Because each call to the `browse` API will return a `Future`

**Comment by redox** [comment]
> Because each call to the browse API will return a Future

Hmmm, yes I see. Any chance you're able to return a `IndexBrowser` object implementing the `Iterator[A]` interface but hiding the `Future` complexity?

**Comment by ElPicador** [comment]
The "right" way to do this in Scala would be to use `Iteratee`.

It will add a dependency to `scalaz`. So, I think it might be a good idea to have this in a project `algoliasearch-helper-scala` or not having it at all in the scala client.

See:
* http://mandubian.com/2012/08/27/understanding-play2-iteratees-for-normal-humans/
* http://eed3si9n.com/learning-scalaz/Iteratees.html

**Comment by ElPicador** [comment]
@redox an opinion on this?

**Comment by redox** [comment]
> @redox an opinion on this?

Indeed, I don't think we want to add an extra dependency here. Are we not able to do something like https://github.com/algolia/algoliasearch-client-ruby/blob/master/lib/algolia/index.rb#L152-L166 ?

**Comment by ElPicador** [comment]
Yes we are, but we will end up with a `Iterable[Future[Iterable[A]]]`, which is not cool at all.

**Comment by ElPicador** [comment]
Ok so for now the Scala client won't implement the full browse method, and so the Delete by query.
