### ISSUE TITLE
Add cross compilation to Scala 2.10

### ISSUE THREAD

**Issue by ElPicador** [algolia/algoliasearch-client-scala#296]

**Comment by ElPicador** [comment]
In scala 2.10.X there is a hard limit for case classes. They can not have more than 22 fields.
The issue is that the classes `IndexSettings` & `Query` have more that 22 fields.

I didn't manage to find a way (with a macro or anything) to be able to work around this issue.

Any one has an idea?

**Comment by aseure** [comment]
Apparently nested tuples or HLists were suggested on SO. Don't know if it will fit though.
http://stackoverflow.com/questions/20258417/how-to-get-around-the-scala-case-class-limit-of-22-fields

**Comment by ElPicador** [comment]
The issue is that it'll break retro compatibility.
And using `HList` would add shapeless as a dependency.

**Comment by ElPicador** [comment]
Too complex, closing this
