### ISSUE TITLE
Incompatibilities with Spark because of json4s

### ISSUE THREAD

**Issue by redox** [algolia/algoliasearch-client-scala#363]
Algolia Scala API client is not compatible with Spark (any version) because of an incompatible version of json4s (Spark#2.0.2 depends on json4s version 3.2.11, Algolia latest client 3.4 and those binaries are incompatible as expressed [here](https://github.com/json4s/json4s/issues/316)). You certainly want to provide an artifact without the json4s dependency or using an older version for Spark compatibility.

cc @framis

**Comment by ElPicador** [comment]
@framis: I've changed the dependency for json4s, could you tell me if this fixes your issue?

**Comment by framis** [comment]
Sure, I'll check tomorrow. Thanks!

**Comment by ElPicador** [comment]
@framis were you able to test it?

**Comment by framis** [comment]
I used com.algolia:scala-client_2.11:1.0.1-SNAPSHOT

I managed to test it (both spark-submit and spark-shell, with Spark version 2.1) and I got this exception 
```
Exception in thread "main" java.lang.NoClassDefFoundError: scoverage/Invoker$
	at algolia.AlgoliaClient.<init>(AlgoliaClient.scala:34)
```

when trying to do
```
val client = new AlgoliaClient("MY_APP_ID", "MY_SECRET")
```

**Comment by ElPicador** [comment]
I made a PR on your code, it works for me locally: https://github.com/framis/spark-algolia/pull/1

**Comment by framis** [comment]
Great! We're good to go, then!

**Comment by ElPicador** [comment]
Ok I'll merge this and release the new version `1.19`
