### ISSUE TITLE
Add cross compilation for json4s 3.2 (spark) & 3.4 (other)

### ISSUE THREAD

**Issue by ElPicador** [algolia/algoliasearch-client-scala#380]

**Comment by ElPicador** [comment]
Found some info but they are old: https://stackoverflow.com/questions/18374362/multi-version-build-with-sbt

**Comment by fucusy** [comment]
I am working Algolia search SDK with spark project meeting lots of dependency conflicts. Need Adding cross complication for json4s 3.2
