### ISSUE TITLE
Missing filters in Ranking to allow configuration of index settings

### ISSUE THREAD

**Issue by jonasanso** [algolia/algoliasearch-client-scala#384]
I intend to create an index sorted by my custom property.
The only way I have found is to include all default Ranking Criteria after my custom ranking. 
```scala
    client.execute {
      settings of conf.index `with` IndexSettings(
        ranking = Some(Seq(Ranking.desc("updated"), Ranking.typo, Ranking.geo, Ranking.words, Ranking.proximity, Ranking.attribute, Ranking.exact))
      )
    }
  }
```
But I found filters missing.

Of course it would be better if I could just add my sorting attribute as we do in the UI. But in any case probably Ranking.filters should still be there for users that want to really change the ranking algorithm. 

This issue is not blocking me in any way. I just report it for completeness.

**Comment by ElPicador** [comment]
Yes you're right. I've created the PR to add this. I'll then release a version `1.22.1`
