### ISSUE TITLE
Provide information on how to contribute

### ISSUE THREAD

**Issue by jlogeart** [algolia/algoliasearch-client-scala#388]
@ElPicador 

I would like to be able to contribute as I have a couple of ideas in mind. 

Yet, I cannot run the tests locally because `AlgoliaTest` requires an `APPLICATION_ID` and an `API_KEY` to be present as environment variables. I could use my company's keys but it does not look like the right strategy.

Is there a process in place so that people can contribute (and somehow run the exiting tests)?

**Comment by ElPicador** [comment]
You can create for free an Algolia account. And you'll find the
APPLICATION_ID and an API_KEY in the dashboard. You'll need to use the
Admin API_KEY to run all the tests.

**Comment by ElPicador** [comment]
Does this work for you?

**Comment by jlogeart** [comment]
It does.

I created an account and a key with all the rights, yet I am seeing a lot of errors when executing the tests:

```
[info] IndexSettingsIntegrationTest:
[info] algolia.integration.IndexSettingsIntegrationTest *** ABORTED ***
[info]   java.lang.NullPointerException:
[info]   at io.netty.resolver.dns.DnsNameResolver.<init>(DnsNameResolver.java:303)
[info]   at io.netty.resolver.dns.DnsNameResolverBuilder.build(DnsNameResolverBuilder.java:379)
[info]   at algolia.AlgoliaHttpClient.<init>(AlgoliaHttpClient.scala:54)
[info]   at algolia.AlgoliaClient.<init>(AlgoliaClient.scala:63)
[info]   at algolia.AlgoliaTest$$anon$1.<init>(AlgoliaTest.scala:50)
[info]   at algolia.AlgoliaTest.<init>(AlgoliaTest.scala:50)
[info]   at algolia.integration.IndexSettingsIntegrationTest.<init>(IndexSettingsIntegrationTest.scala:35)
[info]   at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[info]   at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
[info]   at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[info]   ...
```

I saw some similar errors in Travis.

Here is the result of running `sbt test` after having set the environment variables: https://gist.github.com/jlogeart/7c79d902ec8e15fdfae3ed1f5ad6444f


How can I fix that?

**Comment by jlogeart** [comment]
Yes it does.

I only see errors on the `TCP connect timeout` test:

```
[info] TCP connect timeout
[info] - should answer within 3 seconds *** FAILED ***
[info]   The future returned an exception of type: algolia.AlgoliaClientException, with message: Failed on last retry. (NetworkTest.scala:97)
[info] - should get a result *** FAILED ***
[info]   The future returned an exception of type: algolia.AlgoliaClientException, with message: Failed on last retry. (NetworkTest.scala:105)
```

I have not investigated much yet but I see similar errors in Travis.

**Comment by ElPicador** [comment]
As it's checking that a method is timeouting, sometimes, the timeouts are longer than the ones expected.
Specially on travis, where the machine has low resources.

Basically, you can ignore them, unless you are modifying the timeouts :)

**Comment by ElPicador** [comment]
Can I close this?

**Comment by jlogeart** [comment]
Yes
