### ISSUE TITLE
Partial update not removing fields

### ISSUE THREAD

**Issue by OlafurD** [algolia/algoliasearch-client-scala#419]
Removing fields with partial update does not work. For example, if I have this JSON object in my algolia index:
```json
{
	"name": "oli",
	"email": "oli@example.com",
	"objectID": 33
}
```

and then I execute a partial update:
```scala
val person = Person(objectID = 33, name = Some("oli"), email = None)
client.execute {
 partialUpdate from indexName `object` person
}
```

The email field is not removed from the object

**Comment by ElPicador** [comment]
In Algolia, it's not possible to remove an attribute with a partial update.
If you want to do this you need to update the full object.

Does this answer to your question?

**Comment by OlafurD** [comment]
It does, thanks
