### ISSUE TITLE
Synonym v2 integration

### ISSUE THREAD

**Issue by ElPicador** [algolia/algoliasearch-client-scala#88]
See: https://github.com/algolia/algoliasearch-client-csharp/compare/master...newsynonyms
Trying: 
* `get synonym "syn_id" from "toto"`
* `delete synonym "syn_id" from "toto" and forwardToSlave`
* `clear synonyms of index "toto" and forwardToSlave`
* `search synonyms of "toto" query QuerySynonyms(query = "s")`
* `save synonym Placeholder("oid", "1", Seq("2", "3")) inIndex "toto" and forwardToSlave`
* `save synonyms Seq(Placeholder("oid", "1", Seq("2", "3"))) inIndex "toto" and forwardToSlave and replaceExistingSynonyms`

**Comment by ElPicador** [comment]
WDYT of the syntax?

**Comment by redox** [comment]
> WDYT of the syntax?

LGTM 👍
